#include <sextant/interruptions/idt.h>
#include <sextant/interruptions/irq.h>
#include <sextant/interruptions/handler/handler_tic.h>
#include <sextant/interruptions/handler/handler_clavier.h>
#include <drivers/timer.h>
#include <sextant/Activite/Threads.h>

class Accueil{
public :

	static void initAccueil(EcranV *e){

		EcranV *ecran = e;

		//CADRE
			for(int i = 0; i < HAUTEUR; i++){
				for(int j = 0; j < LARGEUR;j++){
					ecran->afficherCaractere(i,j, NOIR, NOIR, ' ');
				}
			}
			//LIGNE DU HAUT
			ecran->afficherCaractere(0,0, VERT, NOIR, '*');
			ecran->afficherCaractere(0,1, VERT, NOIR, '*');
			ecran->afficherCaractere(0,2, VERT, NOIR, '*');
			ecran->afficherCaractere(0,3, VERT, NOIR, '*');
			ecran->afficherCaractere(0,4, VERT, NOIR, '*');
			ecran->afficherCaractere(0,5, VERT, NOIR, '*');
			ecran->afficherCaractere(0,6, VERT, NOIR, '*');
			ecran->afficherCaractere(0,7, VERT, NOIR, '*');
			ecran->afficherCaractere(0,8, VERT, NOIR, '*');
			ecran->afficherCaractere(0,9, VERT, NOIR, '*');
			ecran->afficherCaractere(0,10, VERT, NOIR, '*');
			ecran->afficherCaractere(0,11, VERT, NOIR, '*');
			ecran->afficherCaractere(0,12, VERT, NOIR, '*');
			ecran->afficherCaractere(0,13, VERT, NOIR, '*');
			ecran->afficherCaractere(0,14, VERT, NOIR, '*');
			ecran->afficherCaractere(0,15, VERT, NOIR, '*');
			ecran->afficherCaractere(0,16, VERT, NOIR, '*');
			ecran->afficherCaractere(0,17, VERT, NOIR, '*');
			ecran->afficherCaractere(0,18, VERT, NOIR, '*');
			ecran->afficherCaractere(0,19, VERT, NOIR, '*');
			ecran->afficherCaractere(0,20, VERT, NOIR, '*');
			ecran->afficherCaractere(0,21, VERT, NOIR, '*');
			ecran->afficherCaractere(0,22, VERT, NOIR, '*');
			ecran->afficherCaractere(0,23, VERT, NOIR, '*');
			ecran->afficherCaractere(0,24, VERT, NOIR, '*');
			ecran->afficherCaractere(0,25, VERT, NOIR, '*');
			ecran->afficherCaractere(0,26, VERT, NOIR, '*');
			ecran->afficherCaractere(0,27, VERT, NOIR, '*');
			ecran->afficherCaractere(0,28, VERT, NOIR, '*');
			ecran->afficherCaractere(0,29, VERT, NOIR, '*');
			ecran->afficherCaractere(0,30, VERT, NOIR, '*');
			ecran->afficherCaractere(0,31, VERT, NOIR, '*');
			ecran->afficherCaractere(0,32, VERT, NOIR, '*');
			ecran->afficherCaractere(0,33, VERT, NOIR, '*');
			ecran->afficherCaractere(0,34, VERT, NOIR, '*');
			ecran->afficherCaractere(0,35, VERT, NOIR, '*');
			ecran->afficherCaractere(0,36, VERT, NOIR, '*');
			ecran->afficherCaractere(0,37, VERT, NOIR, '*');
			ecran->afficherCaractere(0,38, VERT, NOIR, '*');
			ecran->afficherCaractere(0,39, VERT, NOIR, '*');
			ecran->afficherCaractere(0,40, VERT, NOIR, '*');
			ecran->afficherCaractere(0,41, VERT, NOIR, '*');
			ecran->afficherCaractere(0,42, VERT, NOIR, '*');
			ecran->afficherCaractere(0,43, VERT, NOIR, '*');
			ecran->afficherCaractere(0,44, VERT, NOIR, '*');
			ecran->afficherCaractere(0,45, VERT, NOIR, '*');
			ecran->afficherCaractere(0,46, VERT, NOIR, '*');
			ecran->afficherCaractere(0,47, VERT, NOIR, '*');
			ecran->afficherCaractere(0,48, VERT, NOIR, '*');
			ecran->afficherCaractere(0,49, VERT, NOIR, '*');
			ecran->afficherCaractere(0,50, VERT, NOIR, '*');
			ecran->afficherCaractere(0,51, VERT, NOIR, '*');
			ecran->afficherCaractere(0,52, VERT, NOIR, '*');
			ecran->afficherCaractere(0,53, VERT, NOIR, '*');
			ecran->afficherCaractere(0,54, VERT, NOIR, '*');
			ecran->afficherCaractere(0,55, VERT, NOIR, '*');
			ecran->afficherCaractere(0,56, VERT, NOIR, '*');
			ecran->afficherCaractere(0,57, VERT, NOIR, '*');
			ecran->afficherCaractere(0,58, VERT, NOIR, '*');
			ecran->afficherCaractere(0,59, VERT, NOIR, '*');
			ecran->afficherCaractere(0,60, VERT, NOIR, '*');
			ecran->afficherCaractere(0,61, VERT, NOIR, '*');
			ecran->afficherCaractere(0,62, VERT, NOIR, '*');
			ecran->afficherCaractere(0,63, VERT, NOIR, '*');
			ecran->afficherCaractere(0,64, VERT, NOIR, '*');
			ecran->afficherCaractere(0,65, VERT, NOIR, '*');
			ecran->afficherCaractere(0,66, VERT, NOIR, '*');
			ecran->afficherCaractere(0,67, VERT, NOIR, '*');
			ecran->afficherCaractere(0,68, VERT, NOIR, '*');
			ecran->afficherCaractere(0,69, VERT, NOIR, '*');
			ecran->afficherCaractere(0,70, VERT, NOIR, '*');
			ecran->afficherCaractere(0,71, VERT, NOIR, '*');
			ecran->afficherCaractere(0,72, VERT, NOIR, '*');
			ecran->afficherCaractere(0,73, VERT, NOIR, '*');
			ecran->afficherCaractere(0,74, VERT, NOIR, '*');
			ecran->afficherCaractere(0,75, VERT, NOIR, '*');
			ecran->afficherCaractere(0,76, VERT, NOIR, '*');
			ecran->afficherCaractere(0,77, VERT, NOIR, '*');
			ecran->afficherCaractere(0,78, VERT, NOIR, '*');
			ecran->afficherCaractere(0,79, VERT, NOIR, '*');

			//GAUCHE
			ecran->afficherCaractere(1,0, VERT, NOIR, '*');
			ecran->afficherCaractere(2,0, VERT, NOIR, '*');
			ecran->afficherCaractere(3,0, VERT, NOIR, '*');
			ecran->afficherCaractere(4,0, VERT, NOIR, '*');
			ecran->afficherCaractere(5,0, VERT, NOIR, '*');
			ecran->afficherCaractere(6,0, VERT, NOIR, '*');
			ecran->afficherCaractere(7,0, VERT, NOIR, '*');
			ecran->afficherCaractere(8,0, VERT, NOIR, '*');
			ecran->afficherCaractere(9,0, VERT, NOIR, '*');
			ecran->afficherCaractere(10,0, VERT, NOIR, '*');
			ecran->afficherCaractere(11,0, VERT, NOIR, '*');
			ecran->afficherCaractere(12,0, VERT, NOIR, '*');
			ecran->afficherCaractere(13,0, VERT, NOIR, '*');
			ecran->afficherCaractere(14,0, VERT, NOIR, '*');
			ecran->afficherCaractere(15,0, VERT, NOIR, '*');
			ecran->afficherCaractere(16,0, VERT, NOIR, '*');
			ecran->afficherCaractere(17,0, VERT, NOIR, '*');
			ecran->afficherCaractere(18,0, VERT, NOIR, '*');
			ecran->afficherCaractere(19,0, VERT, NOIR, '*');
			ecran->afficherCaractere(20,0, VERT, NOIR, '*');
			ecran->afficherCaractere(21,0, VERT, NOIR, '*');
			ecran->afficherCaractere(22,0, VERT, NOIR, '*');
			ecran->afficherCaractere(23,0, VERT, NOIR, '*');

			//BAS
			ecran->afficherCaractere(24,0, VERT, NOIR, '*');
			ecran->afficherCaractere(24,1, VERT, NOIR, '*');
			ecran->afficherCaractere(24,2, VERT, NOIR, '*');
			ecran->afficherCaractere(24,3, VERT, NOIR, '*');
			ecran->afficherCaractere(24,4, VERT, NOIR, '*');
			ecran->afficherCaractere(24,5, VERT, NOIR, '*');
			ecran->afficherCaractere(24,6, VERT, NOIR, '*');
			ecran->afficherCaractere(24,7, VERT, NOIR, '*');
			ecran->afficherCaractere(24,8, VERT, NOIR, '*');
			ecran->afficherCaractere(24,9, VERT, NOIR, '*');
			ecran->afficherCaractere(24,10, VERT, NOIR, '*');
			ecran->afficherCaractere(24,11, VERT, NOIR, '*');
			ecran->afficherCaractere(24,12, VERT, NOIR, '*');
			ecran->afficherCaractere(24,13, VERT, NOIR, '*');
			ecran->afficherCaractere(24,14, VERT, NOIR, '*');
			ecran->afficherCaractere(24,15, VERT, NOIR, '*');
			ecran->afficherCaractere(24,16, VERT, NOIR, '*');
			ecran->afficherCaractere(24,17, VERT, NOIR, '*');
			ecran->afficherCaractere(24,18, VERT, NOIR, '*');
			ecran->afficherCaractere(24,19, VERT, NOIR, '*');
			ecran->afficherCaractere(24,20, VERT, NOIR, '*');
			ecran->afficherCaractere(24,21, VERT, NOIR, '*');
			ecran->afficherCaractere(24,22, VERT, NOIR, '*');
			ecran->afficherCaractere(24,23, VERT, NOIR, '*');
			ecran->afficherCaractere(24,24, VERT, NOIR, '*');
			ecran->afficherCaractere(24,25, VERT, NOIR, '*');
			ecran->afficherCaractere(24,26, VERT, NOIR, '*');
			ecran->afficherCaractere(24,27, VERT, NOIR, '*');
			ecran->afficherCaractere(24,28, VERT, NOIR, '*');
			ecran->afficherCaractere(24,29, VERT, NOIR, '*');
			ecran->afficherCaractere(24,30, VERT, NOIR, '*');
			ecran->afficherCaractere(24,31, VERT, NOIR, '*');
			ecran->afficherCaractere(24,32, VERT, NOIR, '*');
			ecran->afficherCaractere(24,33, VERT, NOIR, '*');
			ecran->afficherCaractere(24,34, VERT, NOIR, '*');
			ecran->afficherCaractere(24,35, VERT, NOIR, '*');
			ecran->afficherCaractere(24,36, VERT, NOIR, '*');
			ecran->afficherCaractere(24,37, VERT, NOIR, '*');
			ecran->afficherCaractere(24,38, VERT, NOIR, '*');
			ecran->afficherCaractere(24,39, VERT, NOIR, '*');
			ecran->afficherCaractere(24,40, VERT, NOIR, '*');
			ecran->afficherCaractere(24,41, VERT, NOIR, '*');
			ecran->afficherCaractere(24,42, VERT, NOIR, '*');
			ecran->afficherCaractere(24,43, VERT, NOIR, '*');
			ecran->afficherCaractere(24,44, VERT, NOIR, '*');
			ecran->afficherCaractere(24,45, VERT, NOIR, '*');
			ecran->afficherCaractere(24,46, VERT, NOIR, '*');
			ecran->afficherCaractere(24,47, VERT, NOIR, '*');
			ecran->afficherCaractere(24,48, VERT, NOIR, '*');
			ecran->afficherCaractere(24,49, VERT, NOIR, '*');
			ecran->afficherCaractere(24,50, VERT, NOIR, '*');
			ecran->afficherCaractere(24,51, VERT, NOIR, '*');
			ecran->afficherCaractere(24,52, VERT, NOIR, '*');
			ecran->afficherCaractere(24,53, VERT, NOIR, '*');
			ecran->afficherCaractere(24,54, VERT, NOIR, '*');
			ecran->afficherCaractere(24,55, VERT, NOIR, '*');
			ecran->afficherCaractere(24,56, VERT, NOIR, '*');
			ecran->afficherCaractere(24,57, VERT, NOIR, '*');
			ecran->afficherCaractere(24,58, VERT, NOIR, '*');
			ecran->afficherCaractere(24,59, VERT, NOIR, '*');
			ecran->afficherCaractere(24,60, VERT, NOIR, '*');
			ecran->afficherCaractere(24,61, VERT, NOIR, '*');
			ecran->afficherCaractere(24,62, VERT, NOIR, '*');
			ecran->afficherCaractere(24,63, VERT, NOIR, '*');
			ecran->afficherCaractere(24,64, VERT, NOIR, '*');
			ecran->afficherCaractere(24,65, VERT, NOIR, '*');
			ecran->afficherCaractere(24,66, VERT, NOIR, '*');
			ecran->afficherCaractere(24,67, VERT, NOIR, '*');
			ecran->afficherCaractere(24,68, VERT, NOIR, '*');
			ecran->afficherCaractere(24,69, VERT, NOIR, '*');
			ecran->afficherCaractere(24,70, VERT, NOIR, '*');
			ecran->afficherCaractere(24,71, VERT, NOIR, '*');
			ecran->afficherCaractere(24,72, VERT, NOIR, '*');
			ecran->afficherCaractere(24,73, VERT, NOIR, '*');
			ecran->afficherCaractere(24,74, VERT, NOIR, '*');
			ecran->afficherCaractere(24,75, VERT, NOIR, '*');
			ecran->afficherCaractere(24,76, VERT, NOIR, '*');
			ecran->afficherCaractere(24,77, VERT, NOIR, '*');
			ecran->afficherCaractere(24,78, VERT, NOIR, '*');
			ecran->afficherCaractere(24,79, VERT, NOIR, '*');

			//DROITE
			ecran->afficherCaractere(1,79, VERT, NOIR, '*');
			ecran->afficherCaractere(2,79, VERT, NOIR, '*');
			ecran->afficherCaractere(3,79, VERT, NOIR, '*');
			ecran->afficherCaractere(4,79, VERT, NOIR, '*');
			ecran->afficherCaractere(5,79, VERT, NOIR, '*');
			ecran->afficherCaractere(6,79, VERT, NOIR, '*');
			ecran->afficherCaractere(7,79, VERT, NOIR, '*');
			ecran->afficherCaractere(8,79, VERT, NOIR, '*');
			ecran->afficherCaractere(9,79, VERT, NOIR, '*');
			ecran->afficherCaractere(10,79, VERT, NOIR, '*');
			ecran->afficherCaractere(11,79, VERT, NOIR, '*');
			ecran->afficherCaractere(12,79, VERT, NOIR, '*');
			ecran->afficherCaractere(13,79, VERT, NOIR, '*');
			ecran->afficherCaractere(14,79, VERT, NOIR, '*');
			ecran->afficherCaractere(15,79, VERT, NOIR, '*');
			ecran->afficherCaractere(16,79, VERT, NOIR, '*');
			ecran->afficherCaractere(17,79, VERT, NOIR, '*');
			ecran->afficherCaractere(18,79, VERT, NOIR, '*');
			ecran->afficherCaractere(19,79, VERT, NOIR, '*');
			ecran->afficherCaractere(20,79, VERT, NOIR, '*');
			ecran->afficherCaractere(21,79, VERT, NOIR, '*');
			ecran->afficherCaractere(22,79, VERT, NOIR, '*');
			ecran->afficherCaractere(23,79, VERT, NOIR, '*');

			//

			ecran->afficherCaractere(4,2, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(4,3, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(4,4, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(4,5, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(4,6, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(4,7, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(4,8, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(4,9, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(5,2, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(5,3, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(5,4, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(5,5, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(5,6, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(5,7, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(5,8, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(5,9, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(6,2, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(6,3, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(6,8, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(6,9, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(6,66, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(6,67, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(6,68, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(6,69, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(6,70, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(6,71, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(6,72, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,2, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,3, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,8, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,9, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,12, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,13, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,14, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,15, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,16, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,17, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,18, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,19, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,22, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,23, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,24, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,25, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,26, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,27, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,28, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,29, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,32, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,33, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,38, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,39, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,42, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,43, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,44, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,45, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,46, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,47, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,48, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,49, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,52, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,53, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,58, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,59, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,65, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,66, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,67, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,68, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,69, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,70, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,71, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,72, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(7,73, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,2, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,3, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,4, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,5, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,6, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,7, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,8, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,9, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,12, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,13, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,18, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,19, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,22, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,23, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,32, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,33, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,34, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,37, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,38, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,39, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,42, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,43, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,48, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,49, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,52, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,53, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,54, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,58, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,59, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,64, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,65, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,66, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,67, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,68, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,69, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,70, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,71, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(8,72, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,2, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,3, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,4, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,5, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,6, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,7, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,8, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,9, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,12, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,13, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,18, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,19, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,22, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,23, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,32, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,33, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,35, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,36, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,38, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,39, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,42, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,43, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,48, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,49, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,52, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,53, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,55, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,58, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,59, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,63, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,64, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,65, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,66, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,67, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,68, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,69, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(9,75, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,2, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,3, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,12, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,13, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,14, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,15, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,16, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,17, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,18, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,19, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,22, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,23, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,32, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,33, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,38, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,39, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,42, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,43, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,44, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,45, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,46, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,47, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,48, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,49, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,52, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,53, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,56, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,58, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,59, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,63, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,64, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,65, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,66, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,67, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,74, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,75, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(10,76, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,2, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,3, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,12, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,13, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,18, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,19, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,22, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,23, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,32, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,33, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,38, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,39, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,42, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,43, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,48, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,49, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,52, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,53, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,57, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,58, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,59, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,63, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,64, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,65, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,66, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,67, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,68, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,69, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(11,75, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,2, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,3, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,12, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,13, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,18, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,19, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,22, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,23, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,24, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,25, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,26, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,27, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,28, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,29, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,32, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,33, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,38, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,39, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,42, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,43, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,48, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,49, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,52, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,53, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,58, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,59, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,64, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,65, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,66, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,67, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,68, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,69, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,70, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,71, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(12,72, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(13,65, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(13,66, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(13,67, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(13,68, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(13,69, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(13,70, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(13,71, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(13,72, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(13,73, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(14,66, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(14,67, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(14,68, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(14,69, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(14,70, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(14,71, JAUNE, JAUNE, ' ');
			ecran->afficherCaractere(14,72, JAUNE, JAUNE, ' ');

			ecran->afficherCaractere(14,2, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,3, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,4, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,5, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,6, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,7, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,8, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,9, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,10, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,11, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,12, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,13, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,14, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,15, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,16, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,17, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,18, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,19, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,20, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,21, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,22, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,23, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,24, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,25, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,26, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,27, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,28, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,29, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,30, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,31, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,32, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,33, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,34, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,35, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,36, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,37, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,38, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,39, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,40, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,41, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,42, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,43, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,44, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,45, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,46, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,47, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,48, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,49, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,50, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,51, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,52, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,53, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,54, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,55, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,56, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,57, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,58, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,59, NOIR, JAUNE, '_');
			ecran->afficherCaractere(14,60, NOIR, JAUNE, '_');

			//SOULIGNEMENT

			ecran->afficherCaractere(14,2, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,3, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,4, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,5, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,6, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,7, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,8, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,9, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,10, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,11, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,12, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,13, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,14, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,15, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,16, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,17, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,18, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,19, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,20, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,21, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,22, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,23, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,24, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,25, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,26, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,27, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,28, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,29, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,30, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,31, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,32, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,33, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,34, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,35, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,36, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,37, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,38, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,39, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,40, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,41, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,42, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,43, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,44, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,45, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,46, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,47, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,48, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,49, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,50, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,51, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,52, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,53, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,54, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,55, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,56, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,57, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,58, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,59, ROUGE, NOIR, '_');
			ecran->afficherCaractere(14,60, ROUGE, NOIR, '_');

			//FANTOME 1


			ecran->afficherCaractere(16,7, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,8, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,9, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,10, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,11, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,12, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,19, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,20, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,21, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,22, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,23, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,24, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,55, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,56, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,57, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,58, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,59, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,60, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,67, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,68, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,69, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,70, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,71, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(16,72, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(17,6, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(17,13, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(17,18, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(17,25, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(17,54, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(17,61, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(17,66, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(17,73, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,5, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,7, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,8, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,11, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,12, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,14, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,17, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,19, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,20, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,23, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,24, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,26, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,53, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,55, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,56, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,59, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,60, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,62, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,65, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,67, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,68, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,71, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,72, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(18,74, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,5, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,7, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,8, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,11, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,12, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,14, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,17, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,19, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,20, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,23, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,24, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,26, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,53, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,55, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,56, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,59, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,60, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,62, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,65, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,67, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,68, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,71, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,72, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(19,74, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(20,5, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(20,14, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(20,17, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(20,26, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(20,53, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(20,62, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(20,65, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(20,74, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,5, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,7, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,8, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,11, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,12, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,14, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,17, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,19, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,20, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,23, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,24, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,26, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,53, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,55, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,56, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,59, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,60, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,62, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,65, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,67, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,68, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,71, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,72, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(21,74, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,5, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,6, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,9, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,10, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,13, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,14, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,17, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,18, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,21, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,22, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,25, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,26, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,53, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,54, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,57, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,58, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,61, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,62, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,65, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,66, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,69, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,70, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,73, ROUGE, ROUGE, ' ');
			ecran->afficherCaractere(22,74, ROUGE, ROUGE, ' ');

			ecran->afficherMot(16,30,"Bienvenue sur Pacman",CYAN);
			ecran->afficherMot(18,30,"Auteurs : ",GRIS_SOMBRE);
			ecran->afficherMot(19,30,"Alexandre",GRIS_LEGER);
			ecran->afficherMot(19,40,"BERRIAU",GRIS_LEGER);
			ecran->afficherMot(20,30,"Killian",GRIS_LEGER);
			ecran->afficherMot(20,40,"LEHEC",GRIS_LEGER);
			ecran->afficherMot(21,30,"Zakaria",GRIS_LEGER);
			ecran->afficherMot(21,40,"OUALKADI",GRIS_LEGER);
			ecran->afficherMot(22,30,"Francois",GRIS_LEGER);
			ecran->afficherMot(22,40,"VASNIER",GRIS_LEGER);

	}
};
